# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueGtN6JEpdjXv46Ut444GK7YLwMupgZn
"""

import streamlit as st
import joblib
import numpy as np

model = joblib.load("logistic_model.pkl")
scaler = joblib.load("scaler.pkl")
pca = joblib.load("pca.pkl")
kmeans = joblib.load("kmeans.pkl")

st.title("Wine Analysis App")

inputs = []
for feature in range(13):
    inputs.append(st.number_input(f"Feature {feature+1}", value=0.0))

if st.button("Predict"):
    data = np.array(inputs).reshape(1, -1)
    data_scaled = scaler.transform(data)
    data_pca = pca.transform(data_scaled)

    prediction = model.predict(data_scaled)
    cluster = kmeans.predict(data_pca)

    st.success(f"Predicted Class: {prediction[0]}")
    st.info(f"Cluster: {cluster[0]}")