# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtWZzScl-rcWD80a4xeKoJA9OpNA5x0M
"""

import streamlit as st
import numpy as np
import joblib

# Load fitted objects
model = joblib.load("logistic_model.pkl")
scaler = joblib.load("scaler.pkl")
pca = joblib.load("pca.pkl")
kmeans = joblib.load("kmeans.pkl")

st.title("Wine Classification & Clustering")

st.subheader("Enter Wine Features")

inputs = []
for i in range(13):
    val = st.number_input(f"Feature {i+1}", value=0.0)
    inputs.append(val)

if st.button("Predict"):
    data = np.array(inputs).reshape(1, -1)

    # Scale
    data_scaled = scaler.transform(data)

    # Class prediction
    prediction = model.predict(data_scaled)

    # PCA transform (DO NOT FIT again)
    data_pca = pca.transform(data_scaled)

    # Cluster prediction
    cluster = kmeans.predict(data_pca)

    st.success(f"Predicted Wine Class: {prediction[0]}")
    st.info(f"Cluster Assigned: {cluster[0]}")